package com.support_App.enums;

public enum Genre {
    FICTION, SCIENCE, HISTORY, FANTASY, BIOGRAPHY,
    MYSTERY, ROMANCE, HORROR, POETRY, SELF_HELP, PHILOSOPHY,
    RELIGION, ART, COOKING, TRAVEL, HEALTH, BUSINESS, TECHNOLOGY, EDUCATION;
}
